import { Inter } from "next/font/google";
import "@/app/ui/globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "dev_tbtcodeofficial_nextjs@14",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
